# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RookMotionSDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RookMotionSDKSample
  pod 'RookMotionSDK', :git => "https://github.com/RookeriesDevelopment/rook-ios-sdk-training-pod.git", :tag => '1.1.1'
end
