# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatchLink-SDK-Sample' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'RookMotionSDK', :git => "https://github.com/RookeriesDevelopment/rook-ios-sdk-training-pod.git"
  # Pods for WatchLink-SDK-Sample

end

target 'WatchLink-SDK-Sample WatchKit App' do
  use_frameworks!

end

target 'WatchLink-SDK-Sample WatchKit Extension' do
  platform :watchos, '9.0'
  use_frameworks!

  # Pods for WatchLink-SDK-Sample WatchKit Extension
  pod 'RookMotionWatchLink', :git => "https://github.com/RookeriesDevelopment/rook-ios-sdk-training-watch-pod.git"
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '6.2'
    end
  end
end
